[package]
name = "barrier-rust"
version = "0.1.0"
authors = ["Brendan Ball <ball.brendan50@gmail.com>"]
edition = "2018"

[workspace]
members = [".", "parser"]

[dependencies]
hex-literal = "0.2.0"

[dependencies.parser]
path = "parser"
